class AnkletExecutor
{
    public static void main(String[] args)
    {

        Anklet a1=new Anklet();
        a1.weight=1;
        a1.material="Gold";
        a1.hasGems=true;
        a1.diameterCm=5.0;
        a1.colour="Gold Colour";
        a1.sizeInches=7;
        a1.price=8999.0;
        a1.brand="Pothis";
        System.out.println(a1.weight);
        System.out.println(a1.material);
        System.out.println(a1.hasGems);
        System.out.println(a1.diameterCm);
        System.out.println(a1.colour);
        System.out.println(a1.sizeInches);
        System.out.println(a1.price);
        System.out.println(a1.brand);

        Anklet a2=new Anklet();
        a2.weight=2;
        a2.material="Silver";
        a2.hasGems=false;
        a2.diameterCm=4.8;
        a2.colour="Silver Colour";
        a2.sizeInches=6;
        a2.price=3500.0;
        a2.brand="Malabar";
        System.out.println(a2.weight);
        System.out.println(a2.material);
        System.out.println(a2.hasGems);
        System.out.println(a2.diameterCm);
        System.out.println(a2.colour);
        System.out.println(a2.sizeInches);
        System.out.println(a2.price);
        System.out.println(a2.brand);

        Anklet a3=new Anklet();
        a3.weight=3;
        a3.material="Gold";
        a3.hasGems=true;
        a3.diameterCm=5.2;
        a3.colour="Gold Colour";
        a3.sizeInches=7;
        a3.price=9100.0;
        a3.brand="Tanishq";
        System.out.println(a3.weight);
        System.out.println(a3.material);
        System.out.println(a3.hasGems);
        System.out.println(a3.diameterCm);
        System.out.println(a3.colour);
        System.out.println(a3.sizeInches);
        System.out.println(a3.price);
        System.out.println(a3.brand);

        Anklet a4=new Anklet();
        a4.weight=4;
        a4.material="Silver";
        a4.hasGems=false;
        a4.diameterCm=4.6;
        a4.colour="Silver Colour";
        a4.sizeInches=6;
        a4.price=3200.0;
        a4.brand="Kalyan";
        System.out.println(a4.weight);
        System.out.println(a4.material);
        System.out.println(a4.hasGems);
        System.out.println(a4.diameterCm);
        System.out.println(a4.colour);
        System.out.println(a4.sizeInches);
        System.out.println(a4.price);
        System.out.println(a4.brand);

        Anklet a5=new Anklet();
        a5.weight=5;
        a5.material="Gold";
        a5.hasGems=true;
        a5.diameterCm=5.4;
        a5.colour="Gold Colour";
        a5.sizeInches=7;
        a5.price=10000.0;
        a5.brand="Pothis";
        System.out.println(a5.weight);
        System.out.println(a5.material);
        System.out.println(a5.hasGems);
        System.out.println(a5.diameterCm);
        System.out.println(a5.colour);
        System.out.println(a5.sizeInches);
        System.out.println(a5.price);
        System.out.println(a5.brand);

        Anklet a6=new Anklet();
        a6.weight=6;
        a6.material="Silver";
        a6.hasGems=false;
        a6.diameterCm=4.7;
        a6.colour="Silver Colour";
        a6.sizeInches=6;
        a6.price=3400.0;
        a6.brand="Malabar";
        System.out.println(a6.weight);
        System.out.println(a6.material);
        System.out.println(a6.hasGems);
        System.out.println(a6.diameterCm);
        System.out.println(a6.colour);
        System.out.println(a6.sizeInches);
        System.out.println(a6.price);
        System.out.println(a6.brand);

        Anklet a7=new Anklet();
        a7.weight=7;
        a7.material="Gold";
        a7.hasGems=true;
        a7.diameterCm=5.6;
        a7.colour="Gold Colour";
        a7.sizeInches=7;
        a7.price=10500.0;
        a7.brand="Tanishq";
        System.out.println(a7.weight);
        System.out.println(a7.material);
        System.out.println(a7.hasGems);
        System.out.println(a7.diameterCm);
        System.out.println(a7.colour);
        System.out.println(a7.sizeInches);
        System.out.println(a7.price);
        System.out.println(a7.brand);

        Anklet a8=new Anklet();
        a8.weight=8;
        a8.material="Silver";
        a8.hasGems=false;
        a8.diameterCm=4.5;
        a8.colour="Silver Colour";
        a8.sizeInches=6;
        a8.price=3100.0;
        a8.brand="Kalyan";
        System.out.println(a8.weight);
        System.out.println(a8.material);
        System.out.println(a8.hasGems);
        System.out.println(a8.diameterCm);
        System.out.println(a8.colour);
        System.out.println(a8.sizeInches);
        System.out.println(a8.price);
        System.out.println(a8.brand);

        Anklet a9=new Anklet();
        a9.weight=9;
        a9.material="Gold";
        a9.hasGems=true;
        a9.diameterCm=5.7;
        a9.colour="Gold Colour";
        a9.sizeInches=7;
        a9.price=11000.0;
        a9.brand="Pothis";
        System.out.println(a9.weight);
        System.out.println(a9.material);
        System.out.println(a9.hasGems);
        System.out.println(a9.diameterCm);
        System.out.println(a9.colour);
        System.out.println(a9.sizeInches);
        System.out.println(a9.price);
        System.out.println(a9.brand);

        Anklet a10=new Anklet();
        a10.weight=10;
        a10.material="Silver";
        a10.hasGems=false;
        a10.diameterCm=4.4;
        a10.colour="Silver Colour";
        a10.sizeInches=6;
        a10.price=3000.0;
        a10.brand="Malabar";
        System.out.println(a10.weight);
        System.out.println(a10.material);
        System.out.println(a10.hasGems);
        System.out.println(a10.diameterCm);
        System.out.println(a10.colour);
        System.out.println(a10.sizeInches);
        System.out.println(a10.price);
        System.out.println(a10.brand);

        Anklet a11=new Anklet();
        a11.weight=11;
        a11.material="Gold";
        a11.hasGems=true;
        a11.diameterCm=5.8;
        a11.colour="Gold Colour";
        a11.sizeInches=7;
        a11.price=11500.0;
        a11.brand="Tanishq";
        System.out.println(a11.weight);
        System.out.println(a11.material);
        System.out.println(a11.hasGems);
        System.out.println(a11.diameterCm);
        System.out.println(a11.colour);
        System.out.println(a11.sizeInches);
        System.out.println(a11.price);
        System.out.println(a11.brand);

        Anklet a12=new Anklet();
        a12.weight=12;
        a12.material="Silver";
        a12.hasGems=false;
        a12.diameterCm=4.3;
        a12.colour="Silver Colour";
        a12.sizeInches=6;
        a12.price=2900.0;
        a12.brand="Kalyan";
        System.out.println(a12.weight);
        System.out.println(a12.material);
        System.out.println(a12.hasGems);
        System.out.println(a12.diameterCm);
        System.out.println(a12.colour);
        System.out.println(a12.sizeInches);
        System.out.println(a12.price);
        System.out.println(a12.brand);

        Anklet a13=new Anklet();
        a13.weight=13;
        a13.material="Gold";
        a13.hasGems=true;
        a13.diameterCm=5.9;
        a13.colour="Gold Colour";
        a13.sizeInches=7;
        a13.price=11800.0;
        a13.brand="Pothis";
        System.out.println(a13.weight);
        System.out.println(a13.material);
        System.out.println(a13.hasGems);
        System.out.println(a13.diameterCm);
        System.out.println(a13.colour);
        System.out.println(a13.sizeInches);
        System.out.println(a13.price);
        System.out.println(a13.brand);

        Anklet a14=new Anklet();
        a14.weight=14;
        a14.material="Silver";
        a14.hasGems=false;
        a14.diameterCm=4.2;
        a14.colour="Silver Colour";
        a14.sizeInches=6;
        a14.price=2800.0;
        a14.brand="Malabar";
        System.out.println(a14.weight);
        System.out.println(a14.material);
        System.out.println(a14.hasGems);
        System.out.println(a14.diameterCm);
        System.out.println(a14.colour);
        System.out.println(a14.sizeInches);
        System.out.println(a14.price);
        System.out.println(a14.brand);

        Anklet a15=new Anklet();
        a15.weight=15;
        a15.material="Gold";
        a15.hasGems=true;
        a15.diameterCm=6.0;
        a15.colour="Gold Colour";
        a15.sizeInches=7;
        a15.price=12000.0;
        a15.brand="Tanishq";
        System.out.println(a15.weight);
        System.out.println(a15.material);
        System.out.println(a15.hasGems);
        System.out.println(a15.diameterCm);
        System.out.println(a15.colour);
        System.out.println(a15.sizeInches);
        System.out.println(a15.price);
        System.out.println(a15.brand);

        Anklet a16=new Anklet();
        a16.weight=16;
        a16.material="Silver";
        a16.hasGems=false;
        a16.diameterCm=4.1;
        a16.colour="Silver Colour";
        a16.sizeInches=6;
        a16.price=2700.0;
        a16.brand="Kalyan";
        System.out.println(a16.weight);
        System.out.println(a16.material);
        System.out.println(a16.hasGems);
        System.out.println(a16.diameterCm);
        System.out.println(a16.colour);
        System.out.println(a16.sizeInches);
        System.out.println(a16.price);
        System.out.println(a16.brand);

        Anklet a17=new Anklet();
        a17.weight=17;
        a17.material="Gold";
        a17.hasGems=true;
        a17.diameterCm=6.1;
        a17.colour="Gold Colour";
        a17.sizeInches=7;
        a17.price=12500.0;
        a17.brand="Pothis";
        System.out.println(a17.weight);
        System.out.println(a17.material);
        System.out.println(a17.hasGems);
        System.out.println(a17.diameterCm);
        System.out.println(a17.colour);
        System.out.println(a17.sizeInches);
        System.out.println(a17.price);
        System.out.println(a17.brand);

        Anklet a18=new Anklet();
        a18.weight=18;
        a18.material="Silver";
        a18.hasGems=false;
        a18.diameterCm=4.0;
        a18.colour="Silver Colour";
        a18.sizeInches=6;
        a18.price=2600.0;
        a18.brand="Malabar";
        System.out.println(a18.weight);
        System.out.println(a18.material);
        System.out.println(a18.hasGems);
        System.out.println(a18.diameterCm);
        System.out.println(a18.colour);
        System.out.println(a18.sizeInches);
        System.out.println(a18.price);
        System.out.println(a18.brand);

        Anklet a19=new Anklet();
        a19.weight=19;
        a19.material="Gold";
        a19.hasGems=true;
        a19.diameterCm=6.2;
        a19.colour="Gold Colour";
        a19.sizeInches=7;
        a19.price=13000.0;
        a19.brand="Tanishq";
        System.out.println(a19.weight);
        System.out.println(a19.material);
        System.out.println(a19.hasGems);
        System.out.println(a19.diameterCm);
        System.out.println(a19.colour);
        System.out.println(a19.sizeInches);
        System.out.println(a19.price);
        System.out.println(a19.brand);

        Anklet a20=new Anklet();
        a20.weight=20;
        a20.material="Silver";
        a20.hasGems=false;
        a20.diameterCm=3.9;
        a20.colour="Silver Colour";
        a20.sizeInches=6;
        a20.price=2500.0;
        a20.brand="Kalyan";
        System.out.println(a20.weight);
        System.out.println(a20.material);
        System.out.println(a20.hasGems);
        System.out.println(a20.diameterCm);
        System.out.println(a20.colour);
        System.out.println(a20.sizeInches);
        System.out.println(a20.price);
        System.out.println(a20.brand);


        System.out.println();

        Anklet p1=new Anklet(1,"Gold",true,5.0,"Gold Colour",7,8999.0,"Pothis");
        System.out.println(p1.weight);
        System.out.println(p1.material);
        System.out.println(p1.hasGems);
        System.out.println(p1.diameterCm);
        System.out.println(p1.colour);
        System.out.println(p1.sizeInches);
        System.out.println(p1.price);
        System.out.println(p1.brand);

        Anklet p2=new Anklet(2,"Silver",false,4.8,"Silver Colour",6,3500.0,"Malabar");
        System.out.println(p2.weight);
        System.out.println(p2.material);
        System.out.println(p2.hasGems);
        System.out.println(p2.diameterCm);
        System.out.println(p2.colour);
        System.out.println(p2.sizeInches);
        System.out.println(p2.price);
        System.out.println(p2.brand);

        Anklet p3=new Anklet(3,"Gold",true,5.2,"Gold Colour",7,9100.0,"Tanishq");
        System.out.println(p3.weight);
        System.out.println(p3.material);
        System.out.println(p3.hasGems);
        System.out.println(p3.diameterCm);
        System.out.println(p3.colour);
        System.out.println(p3.sizeInches);
        System.out.println(p3.price);
        System.out.println(p3.brand);

        Anklet p4=new Anklet(4,"Silver",false,4.6,"Silver Colour",6,3200.0,"Kalyan");
        System.out.println(p4.weight);
        System.out.println(p4.material);
        System.out.println(p4.hasGems);
        System.out.println(p4.diameterCm);
        System.out.println(p4.colour);
        System.out.println(p4.sizeInches);
        System.out.println(p4.price);
        System.out.println(p4.brand);

        Anklet p5=new Anklet(5,"Gold",true,5.4,"Gold Colour",7,10000.0,"Pothis");
        System.out.println(p5.weight);
        System.out.println(p5.material);
        System.out.println(p5.hasGems);
        System.out.println(p5.diameterCm);
        System.out.println(p5.colour);
        System.out.println(p5.sizeInches);
        System.out.println(p5.price);
        System.out.println(p5.brand);

        Anklet p6=new Anklet(6,"Silver",false,4.7,"Silver Colour",6,3400.0,"Malabar");
        System.out.println(p6.weight);
        System.out.println(p6.material);
        System.out.println(p6.hasGems);
        System.out.println(p6.diameterCm);
        System.out.println(p6.colour);
        System.out.println(p6.sizeInches);
        System.out.println(p6.price);
        System.out.println(p6.brand);

        Anklet p7=new Anklet(7,"Gold",true,5.6,"Gold Colour",7,10500.0,"Tanishq");
        System.out.println(p7.weight);
        System.out.println(p7.material);
        System.out.println(p7.hasGems);
        System.out.println(p7.diameterCm);
        System.out.println(p7.colour);
        System.out.println(p7.sizeInches);
        System.out.println(p7.price);
        System.out.println(p7.brand);

        Anklet p8=new Anklet(8,"Silver",false,4.5,"Silver Colour",6,3100.0,"Kalyan");
        System.out.println(p8.weight);
        System.out.println(p8.material);
        System.out.println(p8.hasGems);
        System.out.println(p8.diameterCm);
        System.out.println(p8.colour);
        System.out.println(p8.sizeInches);
        System.out.println(p8.price);
        System.out.println(p8.brand);

        Anklet p9=new Anklet(9,"Gold",true,5.7,"Gold Colour",7,11000.0,"Pothis");
        System.out.println(p9.weight);
        System.out.println(p9.material);
        System.out.println(p9.hasGems);
        System.out.println(p9.diameterCm);
        System.out.println(p9.colour);
        System.out.println(p9.sizeInches);
        System.out.println(p9.price);
        System.out.println(p9.brand);

        Anklet p10=new Anklet(10,"Silver",false,4.4,"Silver Colour",6,3000.0,"Malabar");
        System.out.println(p10.weight);
        System.out.println(p10.material);
        System.out.println(p10.hasGems);
        System.out.println(p10.diameterCm);
        System.out.println(p10.colour);
        System.out.println(p10.sizeInches);
        System.out.println(p10.price);
        System.out.println(p10.brand);

        Anklet p11=new Anklet(11,"Gold",true,5.8,"Gold Colour",7,11500.0,"Tanishq");
        System.out.println(p11.weight);
        System.out.println(p11.material);
        System.out.println(p11.hasGems);
        System.out.println(p11.diameterCm);
        System.out.println(p11.colour);
        System.out.println(p11.sizeInches);
        System.out.println(p11.price);
        System.out.println(p11.brand);

        Anklet p12=new Anklet(12,"Silver",false,4.3,"Silver Colour",6,2900.0,"Kalyan");
        System.out.println(p12.weight);
        System.out.println(p12.material);
        System.out.println(p12.hasGems);
        System.out.println(p12.diameterCm);
        System.out.println(p12.colour);
        System.out.println(p12.sizeInches);
        System.out.println(p12.price);
        System.out.println(p12.brand);

        Anklet p13=new Anklet(13,"Gold",true,5.9,"Gold Colour",7,11800.0,"Pothis");
        System.out.println(p13.weight);
        System.out.println(p13.material);
        System.out.println(p13.hasGems);
        System.out.println(p13.diameterCm);
        System.out.println(p13.colour);
        System.out.println(p13.sizeInches);
        System.out.println(p13.price);
        System.out.println(p13.brand);

        Anklet p14=new Anklet(14,"Silver",false,4.2,"Silver Colour",6,2800.0,"Malabar");
        System.out.println(p14.weight);
        System.out.println(p14.material);
        System.out.println(p14.hasGems);
        System.out.println(p14.diameterCm);
        System.out.println(p14.colour);
        System.out.println(p14.sizeInches);
        System.out.println(p14.price);
        System.out.println(p14.brand);

        Anklet p15=new Anklet(15,"Gold",true,6.0,"Gold Colour",7,12000.0,"Tanishq");
        System.out.println(p15.weight);
        System.out.println(p15.material);
        System.out.println(p15.hasGems);
        System.out.println(p15.diameterCm);
        System.out.println(p15.colour);
        System.out.println(p15.sizeInches);
        System.out.println(p15.price);
        System.out.println(p15.brand);

        Anklet p16=new Anklet(16,"Silver",false,4.1,"Silver Colour",6,2700.0,"Kalyan");
        System.out.println(p16.weight);
        System.out.println(p16.material);
        System.out.println(p16.hasGems);
        System.out.println(p16.diameterCm);
        System.out.println(p16.colour);
        System.out.println(p16.sizeInches);
        System.out.println(p16.price);
        System.out.println(p16.brand);

        Anklet p17=new Anklet(17,"Gold",true,6.1,"Gold Colour",7,12500.0,"Pothis");
        System.out.println(p17.weight);
        System.out.println(p17.material);
        System.out.println(p17.hasGems);
        System.out.println(p17.diameterCm);
        System.out.println(p17.colour);
        System.out.println(p17.sizeInches);
        System.out.println(p17.price);
        System.out.println(p17.brand);

        Anklet p18=new Anklet(18,"Silver",false,4.0,"Silver Colour",6,2600.0,"Malabar");
        System.out.println(p18.weight);
        System.out.println(p18.material);
        System.out.println(p18.hasGems);
        System.out.println(p18.diameterCm);
        System.out.println(p18.colour);
        System.out.println(p18.sizeInches);
        System.out.println(p18.price);
        System.out.println(p18.brand);

        Anklet p19=new Anklet(19,"Gold",true,6.2,"Gold Colour",7,13000.0,"Tanishq");
        System.out.println(p19.weight);
        System.out.println(p19.material);
        System.out.println(p19.hasGems);
        System.out.println(p19.diameterCm);
        System.out.println(p19.colour);
        System.out.println(p19.sizeInches);
        System.out.println(p19.price);
        System.out.println(p19.brand);

        Anklet p20=new Anklet(20,"Silver",false,3.9,"Silver Colour",6,2500.0,"Kalyan");
        System.out.println(p20.weight);
        System.out.println(p20.material);
        System.out.println(p20.hasGems);
        System.out.println(p20.diameterCm);
        System.out.println(p20.colour);
        System.out.println(p20.sizeInches);
        System.out.println(p20.price);
        System.out.println(p20.brand);

        Anklet p21=new Anklet(21,"Gold",true,6.3,"Gold Colour",7,13500.0,"Pothis");
        System.out.println(p21.weight);
        System.out.println(p21.material);
        System.out.println(p21.hasGems);
        System.out.println(p21.diameterCm);
        System.out.println(p21.colour);
        System.out.println(p21.sizeInches);
        System.out.println(p21.price);
        System.out.println(p21.brand);

        Anklet p22=new Anklet(22,"Silver",false,3.8,"Silver Colour",6,2400.0,"Malabar");
        System.out.println(p22.weight);
        System.out.println(p22.material);
        System.out.println(p22.hasGems);
        System.out.println(p22.diameterCm);
        System.out.println(p22.colour);
        System.out.println(p22.sizeInches);
        System.out.println(p22.price);
        System.out.println(p22.brand);

        Anklet p23=new Anklet(23,"Gold",true,6.4,"Gold Colour",7,14000.0,"Tanishq");
        System.out.println(p23.weight);
        System.out.println(p23.material);
        System.out.println(p23.hasGems);
        System.out.println(p23.diameterCm);
        System.out.println(p23.colour);
        System.out.println(p23.sizeInches);
        System.out.println(p23.price);
        System.out.println(p23.brand);

        Anklet p24=new Anklet(24,"Silver",false,3.7,"Silver Colour",6,2300.0,"Kalyan");
        System.out.println(p24.weight);
        System.out.println(p24.material);
        System.out.println(p24.hasGems);
        System.out.println(p24.diameterCm);
        System.out.println(p24.colour);
        System.out.println(p24.sizeInches);
        System.out.println(p24.price);
        System.out.println(p24.brand);

        Anklet p25=new Anklet(25,"Gold",true,6.5,"Gold Colour",7,14500.0,"Pothis");
        System.out.println(p25.weight);
        System.out.println(p25.material);
        System.out.println(p25.hasGems);
        System.out.println(p25.diameterCm);
        System.out.println(p25.colour);
        System.out.println(p25.sizeInches);
        System.out.println(p25.price);
        System.out.println(p25.brand);

    }
}