class BangleExecutor
{
    public static void main(String[] args)
    {

        Bangle b1 = new Bangle();
        b1.size = 1;
        b1.material="Glass";
        b1.colour="Red";
        b1.weight=20.0;
        b1.price=500.00;
        b1.hasDesign=true;
        b1.brand="Mohits";
        b1.type="Glass";
        System.out.println(b1.size);
        System.out.println(b1.material);
        System.out.println(b1.colour);
        System.out.println(b1.weight);
        System.out.println(b1.price);
        System.out.println(b1.hasDesign);
        System.out.println(b1.brand);
        System.out.println(b1.type);

        Bangle b2 = new Bangle();
        b2.size = 2;
        b2.material="Gold";
        b2.colour="Green";
        b2.weight=21.0;
        b2.price=600.00;
        b2.hasDesign=true;
        b2.brand="Tanishq";
        b2.type="Metal";
        System.out.println(b2.size);
        System.out.println(b2.material);
        System.out.println(b2.colour);
        System.out.println(b2.weight);
        System.out.println(b2.price);
        System.out.println(b2.hasDesign);
        System.out.println(b2.brand);
        System.out.println(b2.type);

        Bangle b3 = new Bangle();
        b3.size = 3;
        b3.material="Plastic";
        b3.colour="Blue";
        b3.weight=18.0;
        b3.price=200.00;
        b3.hasDesign=false;
        b3.brand="Local";
        b3.type="Plastic";
        System.out.println(b3.size);
        System.out.println(b3.material);
        System.out.println(b3.colour);
        System.out.println(b3.weight);
        System.out.println(b3.price);
        System.out.println(b3.hasDesign);
        System.out.println(b3.brand);
        System.out.println(b3.type);

        Bangle b4 = new Bangle();
        b4.size = 4;
        b4.material="Silver";
        b4.colour="White";
        b4.weight=19.5;
        b4.price=750.00;
        b4.hasDesign=true;
        b4.brand="Kalyan";
        b4.type="Metal";
        System.out.println(b4.size);
        System.out.println(b4.material);
        System.out.println(b4.colour);
        System.out.println(b4.weight);
        System.out.println(b4.price);
        System.out.println(b4.hasDesign);
        System.out.println(b4.brand);
        System.out.println(b4.type);

        Bangle b5 = new Bangle();
        b5.size = 5;
        b5.material="Glass";
        b5.colour="Pink";
        b5.weight=17.0;
        b5.price=300.00;
        b5.hasDesign=true;
        b5.brand="Mohits";
        b5.type="Glass";
        System.out.println(b5.size);
        System.out.println(b5.material);
        System.out.println(b5.colour);
        System.out.println(b5.weight);
        System.out.println(b5.price);
        System.out.println(b5.hasDesign);
        System.out.println(b5.brand);
        System.out.println(b5.type);

        Bangle b6 = new Bangle();
        b6.size = 6;
        b6.material="Gold";
        b6.colour="Yellow";
        b6.weight=22.0;
        b6.price=1200.00;
        b6.hasDesign=true;
        b6.brand="Tanishq";
        b6.type="Metal";
        System.out.println(b6.size);
        System.out.println(b6.material);
        System.out.println(b6.colour);
        System.out.println(b6.weight);
        System.out.println(b6.price);
        System.out.println(b6.hasDesign);
        System.out.println(b6.brand);
        System.out.println(b6.type);

        Bangle b7 = new Bangle();
        b7.size = 7;
        b7.material="Plastic";
        b7.colour="Orange";
        b7.weight=16.0;
        b7.price=150.00;
        b7.hasDesign=false;
        b7.brand="Local";
        b7.type="Plastic";
        System.out.println(b7.size);
        System.out.println(b7.material);
        System.out.println(b7.colour);
        System.out.println(b7.weight);
        System.out.println(b7.price);
        System.out.println(b7.hasDesign);
        System.out.println(b7.brand);
        System.out.println(b7.type);

        Bangle b8 = new Bangle();
        b8.size = 8;
        b8.material="Silver";
        b8.colour="Grey";
        b8.weight=20.5;
        b8.price=800.00;
        b8.hasDesign=true;
        b8.brand="Kalyan";
        b8.type="Metal";
        System.out.println(b8.size);
        System.out.println(b8.material);
        System.out.println(b8.colour);
        System.out.println(b8.weight);
        System.out.println(b8.price);
        System.out.println(b8.hasDesign);
        System.out.println(b8.brand);
        System.out.println(b8.type);

        Bangle b9 = new Bangle();
        b9.size = 9;
        b9.material="Glass";
        b9.colour="Purple";
        b9.weight=18.5;
        b9.price=350.00;
        b9.hasDesign=true;
        b9.brand="Mohits";
        b9.type="Glass";
        System.out.println(b9.size);
        System.out.println(b9.material);
        System.out.println(b9.colour);
        System.out.println(b9.weight);
        System.out.println(b9.price);
        System.out.println(b9.hasDesign);
        System.out.println(b9.brand);
        System.out.println(b9.type);

        Bangle b10 = new Bangle();
        b10.size = 10;
        b10.material="Gold";
        b10.colour="Red";
        b10.weight=23.0;
        b10.price=1500.00;
        b10.hasDesign=true;
        b10.brand="Tanishq";
        b10.type="Metal";
        System.out.println(b10.size);
        System.out.println(b10.material);
        System.out.println(b10.colour);
        System.out.println(b10.weight);
        System.out.println(b10.price);
        System.out.println(b10.hasDesign);
        System.out.println(b10.brand);
        System.out.println(b10.type);

        Bangle p1 = new Bangle(1,"Glass","Red",20.0,500.00,true,"Mohits","Glass");
        System.out.println(p1.size);
        System.out.println(p1.material);
        System.out.println(p1.colour);
        System.out.println(p1.weight);
        System.out.println(p1.price);
        System.out.println(p1.hasDesign);
        System.out.println(p1.brand);
        System.out.println(p1.type);

        Bangle p2 = new Bangle(2,"Gold","Green",21.0,600.00,true,"Tanishq","Metal");
        System.out.println(p2.size);
        System.out.println(p2.material);
        System.out.println(p2.colour);
        System.out.println(p2.weight);
        System.out.println(p2.price);
        System.out.println(p2.hasDesign);
        System.out.println(p2.brand);
        System.out.println(p2.type);

        Bangle p3 = new Bangle(3,"Plastic","Blue",18.0,200.00,false,"Local","Plastic");
        System.out.println(p3.size);
        System.out.println(p3.material);
        System.out.println(p3.colour);
        System.out.println(p3.weight);
        System.out.println(p3.price);
        System.out.println(p3.hasDesign);
        System.out.println(p3.brand);
        System.out.println(p3.type);

        Bangle p4 = new Bangle(4,"Silver","White",19.5,750.00,true,"Kalyan","Metal");
        System.out.println(p4.size);
        System.out.println(p4.material);
        System.out.println(p4.colour);
        System.out.println(p4.weight);
        System.out.println(p4.price);
        System.out.println(p4.hasDesign);
        System.out.println(p4.brand);
        System.out.println(p4.type);

        Bangle p5 = new Bangle(5,"Glass","Pink",17.0,300.00,true,"Mohits","Glass");
        System.out.println(p5.size);
        System.out.println(p5.material);
        System.out.println(p5.colour);
        System.out.println(p5.weight);
        System.out.println(p5.price);
        System.out.println(p5.hasDesign);
        System.out.println(p5.brand);
        System.out.println(p5.type);

        Bangle p6 = new Bangle(6,"Gold","Yellow",22.0,1200.00,true,"Tanishq","Metal");
        System.out.println(p6.size);
        System.out.println(p6.material);
        System.out.println(p6.colour);
        System.out.println(p6.weight);
        System.out.println(p6.price);
        System.out.println(p6.hasDesign);
        System.out.println(p6.brand);
        System.out.println(p6.type);

        Bangle p7 = new Bangle(7,"Plastic","Orange",16.0,150.00,false,"Local","Plastic");
        System.out.println(p7.size);
        System.out.println(p7.material);
        System.out.println(p7.colour);
        System.out.println(p7.weight);
        System.out.println(p7.price);
        System.out.println(p7.hasDesign);
        System.out.println(p7.brand);
        System.out.println(p7.type);

        Bangle p8 = new Bangle(8,"Silver","Grey",20.5,800.00,true,"Kalyan","Metal");
        System.out.println(p8.size);
        System.out.println(p8.material);
        System.out.println(p8.colour);
        System.out.println(p8.weight);
        System.out.println(p8.price);
        System.out.println(p8.hasDesign);
        System.out.println(p8.brand);
        System.out.println(p8.type);

        Bangle p9 = new Bangle(9,"Glass","Purple",18.5,350.00,true,"Mohits","Glass");
        System.out.println(p9.size);
        System.out.println(p9.material);
        System.out.println(p9.colour);
        System.out.println(p9.weight);
        System.out.println(p9.price);
        System.out.println(p9.hasDesign);
        System.out.println(p9.brand);
        System.out.println(p9.type);

        Bangle p10 = new Bangle(10,"Gold","Red",23.0,1500.00,true,"Tanishq","Metal");
        System.out.println(p10.size);
        System.out.println(p10.material);
        System.out.println(p10.colour);
        System.out.println(p10.weight);
        System.out.println(p10.price);
        System.out.println(p10.hasDesign);
        System.out.println(p10.brand);
        System.out.println(p10.type);

    }
}