class BeltExecutor{
	public static void main(String[] args){

		Belt belt=new Belt();
		System.out.println("The brand of the belt is: "+belt.brand);
		belt.brand="Levis";
		System.out.println("The brand of the belt is: "+belt.brand);
		System.out.println("The price of the belt is: "+belt.price);
		belt.price=1200;
		System.out.println("The price of the belt is: "+belt.price);
		System.out.println("The colour of the belt is: "+belt.color);
		belt.color="Brown";
		System.out.println("The colour of the belt is: "+belt.color);
		System.out.println("The material of the belt is: "+belt.material);
		belt.material="Leather";
		System.out.println("The material of the belt is: "+belt.material);
		System.out.println("The size of the belt is: "+belt.size);
		belt.size="M";
		System.out.println("The size of the belt is: "+belt.size);
		System.out.println("The buckle type is: "+belt.buckleType);
		belt.buckleType="Pin Buckle";
		System.out.println("The buckle type is: "+belt.buckleType);
		System.out.println("Is reversible: "+belt.reversible);
		belt.reversible=true;
		System.out.println("Is reversible: "+belt.reversible);
		System.out.println("The style is: "+belt.style);
		belt.style="Casual";
		System.out.println("The style is: "+belt.style);
		System.out.println("Manufacturing country: "+belt.manufacturingCountry);
		belt.manufacturingCountry="India";
		System.out.println("Manufacturing country: "+belt.manufacturingCountry);
		System.out.println("Warranty months: "+belt.warrantyMonths);
		belt.warrantyMonths=12;
		System.out.println("Warranty months: "+belt.warrantyMonths);
		System.out.println("Model number: "+belt.modelNumber);
		belt.modelNumber="BLT101";
		System.out.println("Model number: "+belt.modelNumber);
		System.out.println("Release year: "+belt.releaseYear);
		belt.releaseYear="2024";
		System.out.println("Release year: "+belt.releaseYear);
		System.out.println("Leather belt: "+belt.leather);
		belt.leather=true;
		System.out.println("Leather belt: "+belt.leather);
		System.out.println("Adjustable: "+belt.adjustable);
		belt.adjustable=true;
		System.out.println("Adjustable: "+belt.adjustable);
		System.out.println("Texture: "+belt.texture);
		belt.texture="Smooth";
		System.out.println("Texture: "+belt.texture);
		System.out.println("Stitching type: "+belt.stitchingType);
		belt.stitchingType="Double Stitch";
		System.out.println("Stitching type: "+belt.stitchingType);
		System.out.println("Brand logo type: "+belt.brandLogoType);
		belt.brandLogoType="Embossed";
		System.out.println("Brand logo type: "+belt.brandLogoType);
		System.out.println("Buckle material: "+belt.buckleMaterial);
		belt.buckleMaterial="Steel";
		System.out.println("Buckle material: "+belt.buckleMaterial);
		System.out.println("Rust resistant: "+belt.rustResistant);
		belt.rustResistant=true;
		System.out.println("Rust resistant: "+belt.rustResistant);
		System.out.println("Packaging type: "+belt.packagingType);
		belt.packagingType="Box";
		System.out.println("Packaging type: "+belt.packagingType);
		System.out.println("Length in cm: "+belt.lengthInCm);
		belt.lengthInCm=110;
		System.out.println("Length in cm: "+belt.lengthInCm);
		System.out.println("Width in cm: "+belt.widthInCm);
		belt.widthInCm=4;
		System.out.println("Width in cm: "+belt.widthInCm);
		System.out.println("Gender: "+belt.gender);
		belt.gender="Men";
		System.out.println("Gender: "+belt.gender);
		System.out.println("Occasion type: "+belt.occasionType);
		belt.occasionType="Formal";
		System.out.println("Occasion type: "+belt.occasionType);
		System.out.println("Stock available: "+belt.stockAvailable);
		belt.stockAvailable=200;
		System.out.println("Stock available: "+belt.stockAvailable);
	}
}