class ChainLube{
	String brand;
	int price;
	int volumeML;
	String type;
	String color;
	String usage;
	String manufacturingCountry;
	String modelNumber;
	String releaseYear;
	boolean waterproof;
	boolean antiRust;
	boolean dustResistant;
	String packagingType;
	String applicatorType;
	int weightInGrams;
	String smell;
	boolean highTemperatureResistance;
	boolean quickDry;
	String viscosity;
	String compatibility;
	boolean ecoFriendly;
	String storageInstructions;
	int warrantyYears;
	int stockAvailable;
	String distributor;
}