class HairOilExecutor{
	public static void main(String[] args){

		HairOil oil=new HairOil();
		System.out.println("Brand: "+oil.brand);
		oil.brand="Parachute";
		System.out.println("Brand: "+oil.brand);
		System.out.println("Price: "+oil.price);
		oil.price=150;
		System.out.println("Price: "+oil.price);
		System.out.println("Quantity: "+oil.quantityInMl);
		oil.quantityInMl=200;
		System.out.println("Quantity: "+oil.quantityInMl);
		System.out.println("Fragrance: "+oil.fragrance);
		oil.fragrance="Coconut";
		System.out.println("Fragrance: "+oil.fragrance);
		System.out.println("Oil Type: "+oil.oilType);
		oil.oilType="Coconut";
		System.out.println("Oil Type: "+oil.oilType);
		System.out.println("Color: "+oil.color);
		oil.color="Clear";
		System.out.println("Color: "+oil.color);
		System.out.println("Herbal: "+oil.herbal);
		oil.herbal=true;
		System.out.println("Herbal: "+oil.herbal);
		System.out.println("Anti Hair Fall: "+oil.antiHairFall);
		oil.antiHairFall=true;
		System.out.println("Anti Hair Fall: "+oil.antiHairFall);
		System.out.println("Dandruff Control: "+oil.dandruffControl);
		oil.dandruffControl=true;
		System.out.println("Dandruff Control: "+oil.dandruffControl);
		System.out.println("Packaging Type: "+oil.packagingType);
		oil.packagingType="Bottle";
		System.out.println("Packaging Type: "+oil.packagingType);
		System.out.println("Manufacturing Country: "+oil.manufacturingCountry);
		oil.manufacturingCountry="India";
		System.out.println("Manufacturing Country: "+oil.manufacturingCountry);
		System.out.println("Expiry Date: "+oil.expiryDate);
		oil.expiryDate="2027";
		System.out.println("Expiry Date: "+oil.expiryDate);
		System.out.println("Ingredient: "+oil.ingredientMain);
		oil.ingredientMain="Coconut";
		System.out.println("Ingredient: "+oil.ingredientMain);
		System.out.println("Organic: "+oil.organic);
		oil.organic=true;
		System.out.println("Organic: "+oil.organic);
		System.out.println("Paraben Free: "+oil.parabenFree);
		oil.parabenFree=true;
		System.out.println("Paraben Free: "+oil.parabenFree);
		System.out.println("Sulphate Free: "+oil.sulphateFree);
		oil.sulphateFree=true;
		System.out.println("Sulphate Free: "+oil.sulphateFree);
		System.out.println("Hair Type: "+oil.hairType);
		oil.hairType="All";
		System.out.println("Hair Type: "+oil.hairType);
		System.out.println("Bottle Material: "+oil.bottleMaterial);
		oil.bottleMaterial="Plastic";
		System.out.println("Bottle Material: "+oil.bottleMaterial);
		System.out.println("Cap Type: "+oil.capType);
		oil.capType="Flip";
		System.out.println("Cap Type: "+oil.capType);
		System.out.println("Shelf Life: "+oil.shelfLifeMonths);
		oil.shelfLifeMonths=36;
		System.out.println("Shelf Life: "+oil.shelfLifeMonths);
		System.out.println("Texture: "+oil.texture);
		oil.texture="Light";
		System.out.println("Texture: "+oil.texture);
		System.out.println("Absorption Speed: "+oil.absorptionSpeed);
		oil.absorptionSpeed="Fast";
		System.out.println("Absorption Speed: "+oil.absorptionSpeed);
		System.out.println("Model Number: "+oil.modelNumber);
		oil.modelNumber="HO101";
		System.out.println("Model Number: "+oil.modelNumber);
		System.out.println("Release Year: "+oil.releaseYear);
		oil.releaseYear="2024";
		System.out.println("Release Year: "+oil.releaseYear);
		System.out.println("Stock Available: "+oil.stockAvailable);
		oil.stockAvailable=100;
		System.out.println("Stock Available: "+oil.stockAvailable);
	}
}