class HairOil{
	String brand;
	int price;
	double quantityInMl;
	String fragrance;
	String oilType;
	String color;
	boolean herbal;
	boolean antiHairFall;
	boolean dandruffControl;
	String packagingType;
	String manufacturingCountry;
	String expiryDate;
	String ingredientMain;
	boolean organic;
	boolean parabenFree;
	boolean sulphateFree;
	String hairType;
	String bottleMaterial;
	String capType;
	int shelfLifeMonths;
	String texture;
	String absorptionSpeed;
	String modelNumber;
	String releaseYear;
	int stockAvailable;
}