class Hanger{
	String brand;
	int price;
	String material;
	String color;
	String type;
	boolean antiSlip;
	boolean foldable;
	int weightInGrams;
	String manufacturingCountry;
	int quantity;
	String shape;
	boolean rustProof;
	boolean ecoFriendly;
	String packagingType;
	String modelNumber;
	String releaseYear;
	boolean strongHook;
	String hookMaterial;
	boolean rotatingHook;
	String size;
	String design;
	boolean waterproof;
	int warrantyYears;
	int stockAvailable;
	String distributor;
}