class HelmetExecutor{
	public static void main(String[] args){

		Helmet helmet=new Helmet();
		System.out.println("The name of the brand is: "+helmet.brand);
		helmet.brand="SteelBird";
		System.out.println("The name of the brand is: "+helmet.brand);
		System.out.println("The price of the helmet is: "+helmet.price);
		helmet.price=2500;
		System.out.println("The price of the helmet is: "+helmet.price);
		System.out.println("The weight of the helmet is: "+helmet.weightInKg);
		helmet.weightInKg=1.2;
		System.out.println("The weight of the helmet is: "+helmet.weightInKg);
		System.out.println("The colour of the helmet is: "+helmet.colour);
		helmet.colour="Black";
		System.out.println("The colour of the helmet is: "+helmet.colour);
		System.out.println("The size of the helmet is: "+helmet.size);
		helmet.size="M";
		System.out.println("The size of the helmet is: "+helmet.size);
		System.out.println("The type of the helmet is: "+helmet.type);
		helmet.type="Full Face";
		System.out.println("The type of the helmet is: "+helmet.type);
		System.out.println("The material of the helmet is: "+helmet.material);
		helmet.material="ABS";
		System.out.println("The material of the helmet is: "+helmet.material);
		System.out.println("Visor present: "+helmet.visorPresent);
		helmet.visorPresent=true;
		System.out.println("Visor present: "+helmet.visorPresent);
		System.out.println("The visor type is: "+helmet.visorType);
		helmet.visorType="Clear";
		System.out.println("The visor type is: "+helmet.visorType);
		System.out.println("Scratch resistant: "+helmet.scratchResistant);
		helmet.scratchResistant=true;
		System.out.println("Scratch resistant: "+helmet.scratchResistant);
		System.out.println("Anti fog feature: "+helmet.antiFog);
		helmet.antiFog=true;
		System.out.println("Anti fog feature: "+helmet.antiFog);
		System.out.println("Ventilation system present: "+helmet.ventilationSystem);
		helmet.ventilationSystem=true;
		System.out.println("Ventilation system present: "+helmet.ventilationSystem);
		System.out.println("Warranty years: "+helmet.warrantyYears);
		helmet.warrantyYears=2;
		System.out.println("Warranty years: "+helmet.warrantyYears);
		System.out.println("Certification: "+helmet.certification);
		helmet.certification="ISI";
		System.out.println("Certification: "+helmet.certification);
		System.out.println("Bluetooth enabled: "+helmet.bluetoothEnabled);
		helmet.bluetoothEnabled=false;
		System.out.println("Bluetooth enabled: "+helmet.bluetoothEnabled);
		System.out.println("Removable padding: "+helmet.removablePadding);
		helmet.removablePadding=true;
		System.out.println("Removable padding: "+helmet.removablePadding);
		System.out.println("Washable padding: "+helmet.washablePadding);
		helmet.washablePadding=true;
		System.out.println("Washable padding: "+helmet.washablePadding);
		System.out.println("Strap type: "+helmet.strapType);
		helmet.strapType="Double D Ring";
		System.out.println("Strap type: "+helmet.strapType);
		System.out.println("Quick release buckle: "+helmet.quickReleaseBuckle);
		helmet.quickReleaseBuckle=true;
		System.out.println("Quick release buckle: "+helmet.quickReleaseBuckle);
		System.out.println("Interior fabric: "+helmet.interiorFabric);
		helmet.interiorFabric="Soft Foam";
		System.out.println("Interior fabric: "+helmet.interiorFabric);
		System.out.println("UV protection: "+helmet.uvProtection);
		helmet.uvProtection=true;
		System.out.println("UV protection: "+helmet.uvProtection);
		System.out.println("Manufacturing country: "+helmet.manufacturingCountry);
		helmet.manufacturingCountry="India";
		System.out.println("Manufacturing country: "+helmet.manufacturingCountry);
		System.out.println("Model number: "+helmet.modelNumber);
		helmet.modelNumber="SBH-21";
		System.out.println("Model number: "+helmet.modelNumber);
		System.out.println("Release year: "+helmet.releaseYear);
		helmet.releaseYear="2024";
		System.out.println("Release year: "+helmet.releaseYear);
		System.out.println("Stock available: "+helmet.stockAvailable);
		helmet.stockAvailable=50;
		System.out.println("Stock available: "+helmet.stockAvailable);
	}
}