class IronBoxExecutor{
	public static void main(String[] args){

		IronBox ironbox=new IronBox();
		System.out.println("The brand of the iron box is: "+ironbox.brand);
		ironbox.brand="Philips";
		System.out.println("The brand of the iron box is: "+ironbox.brand);
		System.out.println("The price of the iron box is: "+ironbox.price);
		ironbox.price=2000;
		System.out.println("The price of the iron box is: "+ironbox.price);
		System.out.println("The wattage is: "+ironbox.wattage);
		ironbox.wattage=1200;
		System.out.println("The wattage is: "+ironbox.wattage);
		System.out.println("The color is: "+ironbox.color);
		ironbox.color="White";
		System.out.println("The color is: "+ironbox.color);
		System.out.println("The type is: "+ironbox.type);
		ironbox.type="Steam";
		System.out.println("The type is: "+ironbox.type);
		System.out.println("Steam function: "+ironbox.steamFunction);
		ironbox.steamFunction=true;
		System.out.println("Steam function: "+ironbox.steamFunction);
		System.out.println("Non stick plate: "+ironbox.nonStickPlate);
		ironbox.nonStickPlate=true;
		System.out.println("Non stick plate: "+ironbox.nonStickPlate);
		System.out.println("Warranty years: "+ironbox.warrantyYears);
		ironbox.warrantyYears=2;
		System.out.println("Warranty years: "+ironbox.warrantyYears);
		System.out.println("Manufacturing country: "+ironbox.manufacturingCountry);
		ironbox.manufacturingCountry="India";
		System.out.println("Manufacturing country: "+ironbox.manufacturingCountry);
		System.out.println("Auto shut off: "+ironbox.autoShutOff);
		ironbox.autoShutOff=true;
		System.out.println("Auto shut off: "+ironbox.autoShutOff);
		System.out.println("Model number: "+ironbox.modelNumber);
		ironbox.modelNumber="IRN101";
		System.out.println("Model number: "+ironbox.modelNumber);
		System.out.println("Release year: "+ironbox.releaseYear);
		ironbox.releaseYear="2024";
		System.out.println("Release year: "+ironbox.releaseYear);
		System.out.println("Temperature control: "+ironbox.temperatureControl);
		ironbox.temperatureControl=true;
		System.out.println("Temperature control: "+ironbox.temperatureControl);
		System.out.println("Plate material: "+ironbox.plateMaterial);
		ironbox.plateMaterial="Ceramic";
		System.out.println("Plate material: "+ironbox.plateMaterial);
		System.out.println("Vertical steam: "+ironbox.verticalSteam);
		ironbox.verticalSteam=true;
		System.out.println("Vertical steam: "+ironbox.verticalSteam);
		System.out.println("Water tank capacity: "+ironbox.waterTankCapacity);
		ironbox.waterTankCapacity=250;
		System.out.println("Water tank capacity: "+ironbox.waterTankCapacity);
		System.out.println("Cord type: "+ironbox.cordType);
		ironbox.cordType="Power Cord";
		System.out.println("Cord type: "+ironbox.cordType);
		System.out.println("Swivel cord: "+ironbox.swivelCord);
		ironbox.swivelCord=true;
		System.out.println("Swivel cord: "+ironbox.swivelCord);
		System.out.println("Anti drip: "+ironbox.antiDrip);
		ironbox.antiDrip=true;
		System.out.println("Anti drip: "+ironbox.antiDrip);
		System.out.println("Self cleaning: "+ironbox.selfCleaning);
		ironbox.selfCleaning=true;
		System.out.println("Self cleaning: "+ironbox.selfCleaning);
		System.out.println("Packaging type: "+ironbox.packagingType);
		ironbox.packagingType="Box";
		System.out.println("Packaging type: "+ironbox.packagingType);
		System.out.println("Energy rating: "+ironbox.energyRating);
		ironbox.energyRating="5 Star";
		System.out.println("Energy rating: "+ironbox.energyRating);
		System.out.println("Weight in grams: "+ironbox.weightInGrams);
		ironbox.weightInGrams=900;
		System.out.println("Weight in grams: "+ironbox.weightInGrams);
		System.out.println("Handle type: "+ironbox.handleType);
		ironbox.handleType="Comfort Grip";
		System.out.println("Handle type: "+ironbox.handleType);
		System.out.println("Stock available: "+ironbox.stockAvailable);
		ironbox.stockAvailable=120;
		System.out.println("Stock available: "+ironbox.stockAvailable);
	}
}