class KeyChain{
	String brand;
	int price;
	String material;
	String color;
	String type;
	boolean waterproof;
	boolean metalRing;
	String design;
	int weightInGrams;
	String manufacturingCountry;
	String packagingType;
	String modelNumber;
	String releaseYear;
	boolean scratchResistant;
	String shape;
	boolean glowInDark;
	String theme;
	String size;
	boolean ecoFriendly;
	String hookType;
	boolean flexible;
	String texture;
	int warrantyYears;
	int stockAvailable;
	String distributor;
}