class RidingGlovesExecutor{
	public static void main(String[] args){

		RidingGloves gloves=new RidingGloves();
		System.out.println("The brand of the riding gloves is: "+gloves.brand);
		gloves.brand="RoyalEnfield";
		System.out.println("The brand of the riding gloves is: "+gloves.brand);
		System.out.println("The price of the riding gloves is: "+gloves.price);
		gloves.price=2500;
		System.out.println("The price of the riding gloves is: "+gloves.price);
		System.out.println("The size is: "+gloves.size);
		gloves.size="L";
		System.out.println("The size is: "+gloves.size);
		System.out.println("The material is: "+gloves.material);
		gloves.material="Leather";
		System.out.println("The material is: "+gloves.material);
		System.out.println("The color is: "+gloves.color);
		gloves.color="Black";
		System.out.println("The color is: "+gloves.color);
		System.out.println("Waterproof: "+gloves.waterproof);
		gloves.waterproof=true;
		System.out.println("Waterproof: "+gloves.waterproof);
		System.out.println("Touchscreen compatible: "+gloves.touchscreenCompatible);
		gloves.touchscreenCompatible=true;
		System.out.println("Touchscreen compatible: "+gloves.touchscreenCompatible);
		System.out.println("Knuckle protection: "+gloves.knuckleProtection);
		gloves.knuckleProtection=true;
		System.out.println("Knuckle protection: "+gloves.knuckleProtection);
		System.out.println("The style is: "+gloves.style);
		gloves.style="Racing";
		System.out.println("The style is: "+gloves.style);
		System.out.println("Manufacturing country: "+gloves.manufacturingCountry);
		gloves.manufacturingCountry="India";
		System.out.println("Manufacturing country: "+gloves.manufacturingCountry);
		System.out.println("Model number: "+gloves.modelNumber);
		gloves.modelNumber="RG101";
		System.out.println("Model number: "+gloves.modelNumber);
		System.out.println("Release year: "+gloves.releaseYear);
		gloves.releaseYear="2024";
		System.out.println("Release year: "+gloves.releaseYear);
		System.out.println("Breathable: "+gloves.breathable);
		gloves.breathable=true;
		System.out.println("Breathable: "+gloves.breathable);
		System.out.println("Anti slip: "+gloves.antiSlip);
		gloves.antiSlip=true;
		System.out.println("Anti slip: "+gloves.antiSlip);
		System.out.println("Wrist closure type: "+gloves.wristClosureType);
		gloves.wristClosureType="Velcro";
		System.out.println("Wrist closure type: "+gloves.wristClosureType);
		System.out.println("Padding type: "+gloves.paddingType);
		gloves.paddingType="Foam";
		System.out.println("Padding type: "+gloves.paddingType);
		System.out.println("Palm material: "+gloves.palmMaterial);
		gloves.palmMaterial="Leather";
		System.out.println("Palm material: "+gloves.palmMaterial);
		System.out.println("Reflective elements: "+gloves.reflectiveElements);
		gloves.reflectiveElements=true;
		System.out.println("Reflective elements: "+gloves.reflectiveElements);
		System.out.println("Season type: "+gloves.seasonType);
		gloves.seasonType="All Season";
		System.out.println("Season type: "+gloves.seasonType);
		System.out.println("Reinforced fingers: "+gloves.reinforcedFingers);
		gloves.reinforcedFingers=true;
		System.out.println("Reinforced fingers: "+gloves.reinforcedFingers);
		System.out.println("Packaging type: "+gloves.packagingType);
		gloves.packagingType="Box";
		System.out.println("Packaging type: "+gloves.packagingType);
		System.out.println("Gender: "+gloves.gender);
		gloves.gender="Unisex";
		System.out.println("Gender: "+gloves.gender);
		System.out.println("Weight in grams: "+gloves.weightInGrams);
		gloves.weightInGrams=300;
		System.out.println("Weight in grams: "+gloves.weightInGrams);
		System.out.println("Warranty months: "+gloves.warrantyMonths);
		gloves.warrantyMonths=12;
		System.out.println("Warranty months: "+gloves.warrantyMonths);
		System.out.println("Stock available: "+gloves.stockAvailable);
		gloves.stockAvailable=80;
		System.out.println("Stock available: "+gloves.stockAvailable);
	}
}