class RidingGloves{
	String brand;
	int price;
	String size;
	String material;
	String color;
	boolean waterproof;
	boolean touchscreenCompatible;
	boolean knuckleProtection;
	String style;
	String manufacturingCountry;
	String modelNumber;
	String releaseYear;
	boolean breathable;
	boolean antiSlip;
	String wristClosureType;
	String paddingType;
	String palmMaterial;
	boolean reflectiveElements;
	String seasonType;
	boolean reinforcedFingers;
	String packagingType;
	String gender;
	int weightInGrams;
	int warrantyMonths;
	int stockAvailable;
}