class ScrewDriver{
	String brand;
	int price;
	String type;
	String material;
	String color;
	boolean magneticTip;
	boolean insulated;
	int lengthInCm;
	String manufacturingCountry;
	String modelNumber;
	String releaseYear;
	String handleMaterial;
	boolean antiSlipGrip;
	String tipType;
	boolean rustResistant;
	String packagingType;
	int weightInGrams;
	boolean electricianUse;
	boolean interchangeableBits;
	String size;
	String shape;
	String finishType;
	int warrantyYears;
	int stockAvailable;
	String distributor;
}
