class Socks{
	String brand;
	int price;
	String material;
	String color;
	String size;
	String type;
	boolean stretchable;
	boolean breathable;
	String manufacturingCountry;
	String modelNumber;
	String releaseYear;
	boolean sweatAbsorbent;
	String packagingType;
	int weightInGrams;
	String design;
	boolean antiOdor;
	String pattern;
	boolean machineWashable;
	String gender;
	String seasonType;
	boolean ecoFriendly;
	String texture;
	int warrantyYears;
	int stockAvailable;
	String distributor;
}
